# Generated by Django 3.1.7 on 2021-03-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmodels', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='typedanimal',
            constraint=models.CheckConstraint(check=models.Q(name__length__gt=0), name='Animal must have a name'),
        ),
        migrations.AddConstraint(
            model_name='typedanimal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type__exact', 'tmodels.canine'), ('breed__isnull', True)), _negated=True), name='Canines must have a breed'),
        ),
        migrations.AddConstraint(
            model_name='typedanimal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type__exact', 'tmodels.feline'), ('breed__isnull', False)), _negated=True), name='Cats must not have a breed'),
        ),
        migrations.AddConstraint(
            model_name='typedanimal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type__exact', 'tmodels.canine'), ('mice_eaten__gt', 0)), _negated=True), name='Canines must not eat mice'),
        ),
    ]
